### ISSUE TITLE
The number of supported connection when using slow DoS option is static

### ISSUE THREAD

**Issue by 1ms-ms** [stfbk/mqttsa#6]
I have a test setup consisting of 2x ESP32 SpakFun Things and a mosquitto broker setup on my computer (on Ubuntu based VM). I have implemented TLS  on the broker and the brute force attack seems to work fine. However, when I use the slow DoS attack and let's say 12000 of connections, I get 
![image](https://user-images.githubusercontent.com/8413561/158017768-60a59778-df4b-41cd-9f8f-2323a6b40043.png)
The same happens when I use 1000 connections - the max supported connections number does not change. It changes when I set to <338, e.g, when I set to 200, the result is 200. Is it a bug, or do I misunderstand the usage of this option?

**Comment by umorelli** [comment]
Thanks for reporting the issue and sorry for the late reply. 

This meant that MQTTSA couldn't open more than 338 connections - this might be due to the OS not allowing Paho to go further (in that case you could try and change the OS limit as in #7 but I'm seeing a similar limit with Ubuntu 22.04 - no issues on Windows 11 instead) , or there might be a DoS:
- the broker do not allow for more connections in the configuration -> existing clients might be disconnected (depending on the policy).
- the broker did not manage to have more concurrent connected clients -> new clients might be disconnected (depending on the policy).

In both those cases, the broker log could confirm it.
